// -------------------------------声明-------------------------------------------
// <auto-generated>
//     此文件是自动生成的文件，对这个文件的任何修改在下次自动生成的时候都会丢失。
//     模板名称：\TTFiles\TS\Entity\EnumType.tt
//     生成日期：2021-05-31 23:18:00
// </auto-generated>
// ------------------------------------------------------------------------------

import { MDEnum } from "./md/MDEnum";
import { MDEnumItem } from "./md/MDEnumItem";

/**
 * 实体状态枚举 枚举类
 * 实体状态枚举
 */
export enum EnumElementStatus
{
  PND = 1,
  BAK = 2,
  VLD = 3,
  DEL = 4,
  UPD = 5,
  INV = 6,
  AUD = 7,
  SEC = 8
}
/**
 * 枚举元数据：状态
 */
 export class EnumElementStatusMD{

  private static mdEnum: MDEnum;
  
  /**
   * 获取枚举元数据
   * @returns 枚举元数据
   */
  public static GetMDEnum(): MDEnum{
    if(!this.mdEnum){
      this.mdEnum = EnumElementStatusMD.BuildMDEnum();
    }
    return this.mdEnum;
  }
  
  /**
   * 获取枚举对应的元数据：状态
   * @returns 返回元数据对象
   */
  private static BuildMDEnum(): MDEnum{
    const enumType = MDEnum.Create('EnumElementStatus', 'MAF.Core.BizLib.EnumElementStatus', '状态', '状态');
    enumType.PushEnumItem(MDEnumItem.Create('VLD', 'MAF.Core.BizLib.EnumElementStatus:VLD','有效的', '有效的', '3'));
    enumType.PushEnumItem(MDEnumItem.Create('DEL', 'MAF.Core.BizLib.EnumElementStatus:VLD','已删除', '已删除', '4'));
    return enumType;
  }
}